version: '3'
services:
  mongo:
    image: mongo
    container_name: jguwekamongo
    restart: always
  jguweka:
    image: weka/jguweka:OAS3
    restart: always
    links:
      - "mongo:mongodb"
    ports:
      - 8080
    depends_on:
      - mongo
    labels:
      - "service-name:jguweka"
      - "service-type:app-srv"
      - "environment:test"    
  lb:
    image: dockercloud/haproxy
    ports:
      - 80:80
    links:
      - jguweka
    expose:
      - 8080
      - 80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock


      
